apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 3
  serviceName: redis-svc
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:3.2.11-alpine
          ports:
            - containerPort: 6379
              name: redis

        - name: sentinel
          image: redis:3.2.11-alpine
          command: [sh, -c, source /redis-config/sentinel.sh]
          env:
            - name: REDIS_QUORUM
              value: "2"
          volumeMounts:
            - name: config
              mountPath: /redis-config

      volumes:
        - name: config
          configMap:
            name: redis-config
            defaultMode: 420
